name = "Simple"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = ""
homepage = "http://binarin.ru/"
tags = []
features = []
min_version = "0.29"

[author]
  name = ""
  homepage = ""
